name: Build Test Deploy
on:
  push:
    branches: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.13'
    - run: go build
  test:
    needs: build
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.13'
    - run: go test -v 
  deploy:
    needs: [build, test]
    runs-on: ubuntu-20.04
    steps:
    - run: echo "to be deployed"