name: Main Build Test Deploy
on: 
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.13'
    - run: go build
  test:
    needs: build
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.13'
    - run: go test -v 
  deploy:
    needs: [build, test]
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      id-token: write
    steps:
    - id: auth
      name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.3.1
      with:
        token_format: access_token
        workload_identity_provider: ${{ secrets.WID_PROVIDER }}
        service_account: ${{ secrets.AUTH_SERVICE_ACCOUNT }}
    - name: Deploy cloud function
        run: |
          gcloud functions deploy ping-pong-cf \
            --runtime go113 \
            --memory 128MB \
            --trigger-http \
            --region us-central1 \
            --max-instances 1 \
            --security-level secure-always \
            --service-account ${{ secrets.RUNTIME_SERVICE_ACCOUNT }} \
            --allow-unauthenticated